version: "2"
services:
  app:
    build: ./docker/app
    tty: true
    volumes:
      - "./app:/app"
      - app_node_modules:/app/node_modules
    ports:
      - "4000:4000"
volumes:
  app_node_modules: